### PR TITLE
more flexible pins for more recent python versions

### PR DESCRIPTION
**Pull request by bgruening**
Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by bgruening** [comment]
ultimately I would like to get https://github.com/conda-forge/spatialdata-feedstock/pull/5 and later something like https://github.com/conda-forge/squidpy-feedstock/pull/8 merged ... But the pins are to strict and conflicting with each other.

Are those changes ok for you?

**Comment by bgruening** [comment]
@conda-forge-admin please rerender

**Comment by bgruening** [comment]
ping @goanpeca

**Comment by bgruening** [comment]
@jezdez can I merge this one?

@ocefpaf do you think this PR is ok?

**Comment by ocefpaf** [comment]
@bgruening some weeks have passed and the maintainer did not respond. Do you want to also add yourself as a maintainer before we merge this one?

**Comment by bgruening** [comment]
I'm fine with staying incognito 🥸 :-)

**Comment by bgruening** [comment]
Thanks I hope this is ok. Um working on a fix that is 3 layer up the stack ;-)

**Comment by ocefpaf** [comment]
> Thanks I hope this is ok. Um working on a fix that is 3 layer up the stack ;-)

Yep. We usually give folks 1-week. 3 passed, you are good ;-p

**Pull request merged**
